
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.60
distribution_type: module
version: 0.29
name: PITA-XML
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  XML::SAX::ParserFactory: 0.13
  Class::Autouse: 1.23
  IO::Seekable: 0
  IO::File: 0
  IO::String: 1.06
  IO::Handle: 0
  File::Which: 0.05
  Carp: 0
  XML::Validator::Schema: 1.08
  perl: 5.005
  Params::Util: 0.10
  File::ShareDir: 0.02
  XML::SAX::Writer: 0.43
  Data::Digest: 0.02
abstract: Create, load, save and manipulate PITA-XML files
