---
abstract: 'Create, load, save and manipulate PITA-XML files'
author:
  - 'Adam Kennedy <adamk@cpan.org>, L<http://ali.as/>'
build_requires:
  Data::UUID: 1.149
  ExtUtils::MakeMaker: 6.59
  File::Spec: 0.80
  Test::More: 0.47
  Test::XML: 0.08
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PITA::XML
name: PITA-XML
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Carp: 0
  Class::Autouse: 1.23
  Class::Inspector: 1.11
  Config::Tiny: 2.02
  Data::Digest: 0.02
  File::ShareDir: 1.00
  File::Which: 1.07
  IO::File: 0
  IO::Handle: 0
  IO::Seekable: 0
  IO::String: 1.06
  Params::Util: 1.00
  XML::SAX::ParserFactory: 1.01
  XML::SAX::Writer: 0.52
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/PITA-XML
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/PITA-XML
version: 0.52
